### ISSUE TITLE
Suggestion: Better demo

### ISSUE THREAD

**Issue by njt1982** [Decagon/star.js#3]
Given the JS is in the repo anyway, could you make a `gh-pages` branch with a working demo

Linking to https://github.com/Decagon/star.js/blob/master/index.html is not enough for people to see it in action.

All you need is a gh-pages branch with that HTML and a copy of the relevant JS...

**Comment by njt1982** [comment]
I have made a branch - but cant seem to make a PR for it...

https://github.com/Decagon/star.js/compare/gh-pages...njt1982:gh-pages

Make because there is no gh-pages branch to PR against?

**Comment by njt1982** [comment]
```
git checkout --orphan gh-pages
git checkout master -- index.html star.js
git add index.html star.js
git ci -m "Adding index and star"
git push -u origin gh-pages
```

^^ This is how I made it.

Then you can update the README to point at your equivalent of https://njt1982.github.io/star.js/

**Comment by alexyorke** [comment]
Thanks! I got this working now from your commands: https://decagon.github.io/star.js/

The PR problem was probably because (as you said) my lack of a gh-pages branch which you couldn't push to.

**Comment by njt1982** [comment]
Aces - thanks :)
